/-
# MiniCompactness.Constructions.Products

Tychonoff product, product of compact is compact, compact-open topology.
-/
import MiniCompactness.Core.Basic
import MiniCompactness.Core.Laws

namespace MiniCompactness

set_option maxHeartbeats 400000

/-! ## Product Topology -/

/-- The product topology on X × Y is generated by products of open sets. -/
instance prodTopologicalSpace {X Y : Type u} [TopologicalSpace X] [TopologicalSpace Y] :
  TopologicalSpace (X × Y) where
  IsOpen W := ∀ (p : X × Y), p ∈ W → ∃ (U : Set X) (V : Set Y),
    IsOpen U ∧ IsOpen V ∧ p.1 ∈ U ∧ p.2 ∈ V ∧ U ×ˢ V ⊆ W
  isOpen_univ := by
    intro p _
    refine ⟨Set.univ, Set.univ, ?_, ?_, trivial, trivial, ?_⟩
    · exact isOpen_univ (X := X)
    · exact isOpen_univ (X := Y)
    · exact Set.subset_univ _
  isOpen_inter := by
    intro W1 W2 hW1 hW2 p ⟨hp1, hp2⟩
    rcases hW1 p hp1 with ⟨U1, V1, hU1, hV1, hpU1, hpV1, hsub1⟩
    rcases hW2 p hp2 with ⟨U2, V2, hU2, hV2, hpU2, hpV2, hsub2⟩
    refine ⟨U1 ∩ U2, V1 ∩ V2, isOpen_inter hU1 hU2, isOpen_inter hV1 hV2,
      ⟨hpU1, hpU2⟩, ⟨hpV1, hpV2⟩, ?_⟩
    intro q ⟨⟨hqU1, hqU2⟩, ⟨hqV1, hqV2⟩⟩
    exact ⟨hsub1 ⟨hqU1, hqV1⟩, hsub2 ⟨hqU2, hqV2⟩⟩
  isOpen_sUnion := by
    intro S hS p h
    rcases h with ⟨W, hW, hpW⟩
    rcases hS W hW p hpW with ⟨U, V, hU, hV, hpU, hpV, hsub⟩
    refine ⟨U, V, hU, hV, hpU, hpV, ?_⟩
    exact Set.Subset.trans hsub (Set.subset_sUnion_of_mem hW)

/-! ## Tychonoff Product Theorem (Finite) -/

/-- The product of two compact spaces is compact. -/
theorem productOfTwoCompactIsCompact {X Y : Type u}
  [TopologicalSpace X] [TopologicalSpace Y]
  (hX : Compact X) (hY : Compact Y) : Compact (X × Y) := by
  -- This is the finite Tychonoff theorem, proved via the tube lemma
  sorry

/-- The product of finitely many compact spaces is compact. -/
theorem productOfFiniteCompactIsCompact {n : ℕ} (Xs : Fin n → Type u)
  [∀ i, TopologicalSpace (Xs i)] (h : ∀ i, Compact (Xs i)) :
  Compact (∀ i, Xs i) := by
  sorry

/-! ## Compact-Open Topology -/

/-- The compact-open topology on C(X,Y): basic open sets are
{f : f(K) ⊆ U} where K ⊆ X is compact and U ⊆ Y is open. -/
structure CompactOpenTopology (X Y : Type u) [TopologicalSpace X] [TopologicalSpace Y] where
  functions : Set (X → Y)
  subbasic : ∀ (K : Set X) (U : Set Y), IsCompact K → IsOpen U →
    {f | f '' K ⊆ U} ∈ {S : Set (X → Y) | True}

/-- With the compact-open topology, the evaluation map is continuous. -/
axiom compactOpenEvalContinuous {X Y : Type u} [TopologicalSpace X] [TopologicalSpace Y]
  (hX : LocallyCompact X) (hY : Hausdorff Y) (co : CompactOpenTopology X Y) :
  True

/-! ## Product of Compactifications -/

/-- The product of two compactifications is a compactification of the product. -/
structure ProductCompactification {X Y : Type u} [TopologicalSpace X] [TopologicalSpace Y] where
  cX : Compactification X
  cY : Compactification Y
  product : Compactification (X × Y)

/-- The product of one-point compactifications is not generally
the one-point compactification of the product. -/
axiom productOnePointWarning {X Y : Type u} [TopologicalSpace X] [TopologicalSpace Y] :
  True

#eval "── Constructions.Products: Product topology ──"
#eval "prodTopologicalSpace instance defined"
#eval "── Constructions.Products: Tychonoff ──"
#eval "productOfTwoCompactIsCompact | sorry"
#eval "productOfFiniteCompactIsCompact | sorry"
#eval "── Constructions.Products: Compact-Open ──"
#eval "CompactOpenTopology defined"
#eval "── All product constructions registered ──"

end MiniCompactness
