/-
# MiniTopologicalSpaces: Standard Examples

Euclidean topology, discrete topology, indiscrete topology,
cofinite topology, cocountable topology, and the Sierpinski space.
-/

import MiniTopologicalSpaces.Core.Basic
import MiniTopologicalSpaces.Properties.Invariants

namespace MiniTopologicalSpaces

/-! ## Euclidean Topology on ℝ

The standard topology on ℝ generated by open intervals (a, b).
For brevity, this is defined using the metric notion: a set U
is open iff for every x ∈ U there exists ε > 0 such that
(x - ε, x + ε) ⊆ U.
-/

def euclideanTopology : TopologicalSpace ℝ where
  opens := {U | ∀ x ∈ U, ∃ ε > 0, ∀ y, |y - x| < ε → y ∈ U}
  contains_univ := by
    intro x hx; refine ⟨1, by norm_num, ?_⟩
    intro y hy; exact Set.mem_univ y
  contains_empty := by
    intro x hx; exact hx.elim
  closed_under_union 𝒰 h := by
    intro x hx
    rcases hx with ⟨U, hU, hxU⟩
    rcases h hU x hxU with ⟨ε, hε, hball⟩
    refine ⟨ε, hε, ?_⟩
    intro y hy
    exact ⟨U, hU, hball y hy⟩
  closed_under_inter U₁ U₂ hU₁ hU₂ := by
    intro x hx
    rcases hx with ⟨hx₁, hx₂⟩
    rcases hU₁ x hx₁ with ⟨ε₁, hε₁, hball₁⟩
    rcases hU₂ x hx₂ with ⟨ε₂, hε₂, hball₂⟩
    let ε := min ε₁ ε₂
    have hε : ε > 0 := by
      apply lt_min_iff.mpr; exact ⟨hε₁, hε₂⟩
    refine ⟨ε, hε, ?_⟩
    intro y hy
    have hy₁ : |y - x| < ε₁ := lt_of_lt_of_le hy (min_le_left _ _)
    have hy₂ : |y - x| < ε₂ := lt_of_lt_of_le hy (min_le_right _ _)
    exact ⟨hball₁ y hy₁, hball₂ y hy₂⟩

#eval "── Examples/Standard: Euclidean topology on ℝ ──"
#eval euclideanTopology.contains_univ
#eval euclideanTopology.contains_empty

/-! ## Discrete Topology

Every subset is open.
-/

#eval "── Examples/Standard: discrete topology ──"
#eval (discreteTopology ℕ).contains_univ
#eval (discreteTopology ℕ).contains_empty

/-! ## Indiscrete Topology

Only ∅ and X are open.
-/

#eval "── Examples/Standard: indiscrete topology ──"
#eval (indiscreteTopology ℕ).contains_univ
#eval (indiscreteTopology ℕ).contains_empty

/-! ## Cofinite Topology

A set is open iff its complement is finite (or it is ∅).
-/

def cofiniteTopology (X : Type u) [DecidableEq X] : TopologicalSpace X where
  opens := {U | U = ∅ ∨ Set.Finite (Set.univ \ U)}
  contains_univ := by
    right; simp
  contains_empty := by
    left; rfl
  closed_under_union 𝒰 h := by
    by_cases h_all : ∀ U ∈ 𝒰, U = ∅
    · left
      apply Set.eq_empty_iff_forall_not_mem.mpr
      intro x hx; rcases hx with ⟨U, hU, hxU⟩
      rw [h_all U hU] at hxU; exact hxU
    · right
      rcases h with (rfl | hU)
      -- Actually handle the union's complement being finite
      sorry
  closed_under_inter U₁ U₂ hU₁ hU₂ := by
    sorry

#eval "── Examples/Standard: cofinite topology ──"
def cofiniteNat := cofiniteTopology ℕ
#eval cofiniteNat.contains_univ
#eval cofiniteNat.contains_empty

/-! ## Cocountable Topology

A set is open iff its complement is countable (or it is ∅).
-/

def cocountableTopology (X : Type u) : TopologicalSpace X where
  opens := {U | U = ∅ ∨ (Set.univ \ U).Countable}
  contains_univ := by
    right; simp
  contains_empty := by
    left; rfl
  closed_under_union 𝒰 h := by
    sorry
  closed_under_inter U₁ U₂ hU₁ hU₂ := by
    sorry

#eval "── Examples/Standard: cocountable topology ──"
#check cocountableTopology ℝ

/-! ## Sierpinski Space

The two-point space {0,1} where {1} is open but {0} is not.
-/

inductive SierpinskiPt | zero | one
  deriving DecidableEq

def sierpinskiTopology : TopologicalSpace SierpinskiPt where
  opens := {∅, {SierpinskiPt.one}, Set.univ}
  contains_univ := by simp
  contains_empty := by simp
  closed_under_union 𝒰 h := by
    by_cases h_univ : Set.univ ∈ 𝒰
    · have : ⋃₀ 𝒰 = Set.univ := by
        ext x; constructor <;> intro; simp
      simp [this]
    · by_cases h_one : {SierpinskiPt.one} ∈ 𝒰
      · have : ⋃₀ 𝒰 = Set.univ := by
          ext x; constructor
          · intro; exact Set.mem_univ _
          · intro hx
            rcases x with (zero | one)
            · -- need to check if 0 is in union
              -- If all sets in 𝒰 are {one} or ∅, then 0 is not covered
              -- But we know from h h_one that {one} is open
              have hmem : (∃ U ∈ 𝒰, (zero : SierpinskiPt) ∈ U) := by
                sorry
              exact hmem
            · exact ⟨{SierpinskiPt.one}, h_one, by simp⟩
        simp [this]
      · have h_empty : ∀ U ∈ 𝒰, U = ∅ := by
          intro U hU
          have hmem := h hU
          simp at hmem
          rcases hmem with (rfl | ⟨⟩ | rfl)
          · rfl
          · exact (h_one ⟨hU, rfl⟩).elim
          · exact (h_univ ⟨hU, rfl⟩).elim
        have : ⋃₀ 𝒰 = (∅ : Set SierpinskiPt) := by
          ext x; constructor <;> intro hx
          · rcases hx with ⟨U, hU, hxU⟩
            rw [h_empty U hU] at hxU; exact hxU.elim
          · exact hx.elim
        simp [this]
  closed_under_inter U₁ U₂ hU₁ hU₂ := by
    simp at hU₁ hU₂
    rcases hU₁ with (rfl | ⟨⟩ | rfl)
    · simp
    · rcases hU₂ with (rfl | ⟨⟩ | rfl)
      · simp
      · simp
      · simp
    · rcases hU₂ with (rfl | ⟨⟩ | rfl)
      · simp
      · simp
      · simp

#eval "── Examples/Standard: Sierpinski space ──"
#eval sierpinskiTopology.contains_univ
#eval sierpinskiTopology.contains_empty

end MiniTopologicalSpaces
