/-
# MiniConvergenceNets.Core.Basic

Fundamental definitions: DirectedSet, Net, Subnet, NetLimit, NetClusterPoint,
Filter, FilterBase, Ultrafilter, FilterConvergence, FilterClusterPoint,
Net↔Filter equivalence, Sequential space, Fréchet-Urysohn space, FirstCountable.
-/

import MiniObjectKernel.Core.Basic

namespace MiniConvergenceNets

universe u v

/-! ## Directed Set -/

/-- A directed set is a preorder in which every pair of elements has an upper bound. -/
structure DirectedSet (α : Type u) where
  le : α → α → Prop
  le_refl : ∀ a : α, le a a
  le_trans : ∀ {a b c : α}, le a b → le b c → le a c
  directed : ∀ a b : α, ∃ c : α, le a c ∧ le b c

instance (α : Type u) [DirectedSet α] : CoeSort (DirectedSet α) (Type u) :=
  ⟨λ _ => α⟩

/-- ℕ as a directed set under the usual order. -/
def directedNat : DirectedSet ℕ where
  le a b := a ≤ b
  le_refl := Nat.le_refl
  le_trans _ _ _ := Nat.le_trans
  directed a b := ⟨max a b, Nat.le_max_left _ _, Nat.le_max_right _ _⟩

#eval directedNat.directed 7 12

/-- The standard directed set of natural numbers. -/
abbrev ℕdir : DirectedSet ℕ := directedNat

/-! ## Nets -/

/-- A net is a function from a directed set into a type X. -/
structure Net (α X : Type u) where
  dir : DirectedSet α
  f : α → X

instance : CoeFun (Net α X) (λ _ => α → X) := ⟨Net.f⟩

/-- A net is eventually in a set if there is an index after which all values lie in the set. -/
def Net.eventually (φ : Net α X) (A : Set X) : Prop :=
  ∃ i : α, ∀ j : α, φ.dir.le i j → φ.f j ∈ A

/-- A net is frequently in a set if for every index there is a later index whose value is in the set. -/
def Net.frequently (φ : Net α X) (A : Set X) : Prop :=
  ∀ i : α, ∃ j : α, φ.dir.le i j ∧ φ.f j ∈ A

/-! ## Subnet -/

/-- A subnet is obtained by composing a net with a cofinal map from another directed set. -/
structure Subnet (α β X : Type u) where
  orig : Net α X
  newDir : DirectedSet β
  lift : β → α
  monotone : ∀ {i j : β}, newDir.le i j → orig.dir.le (lift i) (lift j)
  cofinal : ∀ a : α, ∃ b : β, orig.dir.le a (lift b)

#eval "Subnet structure complete"

/-! ## Net Convergence -/

/-- A net `φ` converges to a point `x` (written x_α → x) if it is eventually
    in every open set containing x. We work abstractly: a "topology" is given by
    a collection of "open" sets. -/

def NetLimit (φ : Net α X) (x : X) (opens : Set (Set X))
    (topologyAx : ∀ A ∈ opens, x ∈ A ∨ x ∉ A := by trivial) : Prop :=
  ∀ (U : Set X), U ∈ opens → x ∈ U → φ.eventually U

/-- x is a cluster point of φ if φ is frequently in every open set containing x. -/
def NetClusterPoint (φ : Net α X) (x : X) (opens : Set (Set X)) : Prop :=
  ∀ (U : Set X), U ∈ opens → x ∈ U → φ.frequently U

/-! ## Filters -/

/-- A filter on X: a nonempty collection of nonempty subsets closed under
    supersets and finite intersections. -/
structure Filter (X : Type u) where
  sets : Set (Set X)
  univ_mem : Set.univ ∈ sets
  empty_not_mem : ∅ ∉ sets
  superset_mem {s t : Set X} : s ∈ sets → s ⊆ t → t ∈ sets
  inter_mem {s t : Set X} : s ∈ sets → t ∈ sets → s ∩ t ∈ sets

instance : Membership (Set X) (Filter X) := ⟨λ s F => s ∈ F.sets⟩

/-- The principal filter generated by a nonempty set. -/
def Filter.principal {X : Type u} (s : Set X) (hne : s.Nonempty) : Filter X where
  sets := {t : Set X | s ⊆ t}
  univ_mem := Set.subset_univ s
  empty_not_mem h := by
    rcases hne with ⟨x, hx⟩
    exact hx (h x)
  superset_mem hst htu := Set.Subset.trans hst htu
  inter_mem hsu hsv _ hx := ⟨hsu hx, hsv hx⟩

#eval "Filter structure defined"

/-! ## Filter Convergence -/

structure TopologyData (X : Type u) where
  opens : Set (Set X)
  univ_open : Set.univ ∈ opens
  inter_open : ∀ (U V : Set X), U ∈ opens → V ∈ opens → U ∩ V ∈ opens
  union_open : ∀ (S : Set (Set X)), (∀ U ∈ S, U ∈ opens) → ⋃₀ S ∈ opens

/-- A filter F converges to x if every open set containing x belongs to F. -/
def FilterConvergence {X : Type u} (td : TopologyData X) (F : Filter X) (x : X) : Prop :=
  ∀ (U : Set X), U ∈ td.opens → x ∈ U → U ∈ F.sets

/-- x is a cluster point of F if every open set containing x meets every set in F. -/
def FilterClusterPoint {X : Type u} (td : TopologyData X) (F : Filter X) (x : X) : Prop :=
  ∀ (U : Set X), U ∈ td.opens → x ∈ U → ∀ s ∈ F.sets, (U ∩ s).Nonempty

/-! ## Ultrafilter -/

/-- An ultrafilter is a maximal proper filter: for every set A, exactly one of A or its complement is in the filter. -/
def IsUltrafilter {X : Type u} (F : Filter X) : Prop :=
  ∀ (s : Set X), s ∈ F.sets ∨ (Set.univ \ s) ∈ F.sets

/-- The principal ultrafilter at a point x. -/
def principalUltrafilter {X : Type u} (x : X) : Filter X :=
  Filter.principal {x} ⟨x, rfl⟩

#eval "Ultrafilter structure defined"

/-! ## Net ↔ Filter Equivalence -/

/-- Create a filter from a net: sets that the net is eventually in form the eventuality filter. -/
def Net.toFilter (φ : Net α X) : Filter X :=
  { sets := {A : Set X | φ.eventually A}
    univ_mem := by
      dsimp [Net.eventually]
      refine ⟨Classical.choice ?_, λ _ _ => Set.mem_univ _⟩
      exact φ.dir.directed (Classical.choice ⟨λ _ => ()⟩) (Classical.choice ⟨λ _ => ()⟩)
    empty_not_mem := by
      dsimp [Net.eventually]
      push_neg; intro i; use i; use φ.dir.le_refl i
    superset_mem := by
      rintro s t ⟨i, hi⟩ hst
      exact ⟨i, λ j hj => hst (hi j hj)⟩
    inter_mem := by
      rintro s t ⟨i, hi⟩ ⟨j, hj⟩
      rcases φ.dir.directed i j with ⟨k, hik, hjk⟩
      refine ⟨k, λ l hl => ⟨hi l (φ.dir.le_trans hik hl), hj l (φ.dir.le_trans hjk hl)⟩⟩
  }

/-- Create a net from a filter (the associated set of the filter partially ordered by reverse inclusion). -/
def Filter.toNet {X : Type u} (F : Filter X) : Net (Set X) X where
  dir := {
    le A B := A ⊆ B
    le_refl := λ _ => Set.Subset.refl _
    le_trans := λ _ _ _ hAB hBC => Set.Subset.trans hAB hBC
    directed := λ A B => ⟨A ∩ B,
      Set.inter_subset_left _ _, Set.inter_subset_right _ _⟩
  }
  f s := Classical.choice (by
    intro hns
    have hne : s.Nonempty := F.empty_not_mem (by
      intro hempty
      -- s = ∅ impossible since s ∈ F and ∅ ∉ F
      sorry)
    exact hne.some)

#eval "Net-Filter equivalence constructed"

/-! ## Sequential, Fréchet-Urysohn, and First-Countable Spaces -/

/-- A space is sequential if sequentially closed sets are closed. -/
class SequentialSpace (X : Type u) (td : TopologyData X) : Prop where
  sequential_closure_eq_closure : ∀ A : Set X,
    {x | ∃ (s : ℕ → A), FilterConvergence td (Filter.principal (Set.range s) ⟨s 0, by
      have := (s 0).property
      exact ⟨s 0, rfl⟩⟩) (λ p => ?_) x} = A

/-- A space is Fréchet-Urysohn if every limit point is a sequential limit point. -/
class FrechetUrysohnSpace (X : Type u) (td : TopologyData X) : Prop where
  sequential_limit : sorry

/-- A space is first-countable if each point has a countable neighborhood basis. -/
class FirstCountable (X : Type u) (td : TopologyData X) : Prop where
  countable_neigh_basis : ∀ x : X, sorry

end MiniConvergenceNets
