/-
# MiniTopologicalSpaces: Product Topology

Defines the product topology (Tychonoff topology), the box topology,
and projection maps for arbitrary families of topological spaces.
-/

import MiniTopologicalSpaces.Core.Basic
import MiniTopologicalSpaces.Morphisms.Hom

namespace MiniTopologicalSpaces

/-! ## Product Topology (Tychonoff)

For a family of spaces X_i, the product topology on ∏ X_i is
generated by sets of the form ∏ U_i where U_i = X_i for all but
finitely many i, and each U_i is open in X_i.
-/

/-! ## Binary Product Topology -/

def prodTopology (X Y : Type u) [tX : TopologicalSpace X] [tY : TopologicalSpace Y] :
    TopologicalSpace (X × Y) where
  opens := {W | ∀ (x, y) ∈ W, ∃ (U : Set X) (V : Set Y),
    U ∈ tX.opens ∧ V ∈ tY.opens ∧ x ∈ U ∧ y ∈ V ∧ U ×ˢ V ⊆ W}
  contains_univ := by
    intro p hp
    exact ⟨Set.univ, Set.univ, tX.contains_univ, tY.contains_univ,
      by trivial, by trivial, by intro q hq; exact Set.mem_univ _⟩
  contains_empty := by
    intro p hp
    exact hp.elim
  closed_under_union 𝒰 h := by
    intro p hp
    rcases hp with ⟨W, hW, hpW⟩
    rcases h hW p hpW with ⟨U, V, hUX, hVY, hxU, hyV, h_sub⟩
    exact ⟨U, V, hUX, hVY, hxU, hyV, Set.Subset.trans h_sub (by
      intro q hq; exact ⟨W, hW, hq⟩)⟩
  closed_under_inter W₁ W₂ hW₁ hW₂ := by
    intro p hp
    rcases hp with ⟨hp₁, hp₂⟩
    rcases hW₁ p hp₁ with ⟨U₁, V₁, hU₁, hV₁, hxU₁, hyV₁, hsub₁⟩
    rcases hW₂ p hp₂ with ⟨U₂, V₂, hU₂, hV₂, hxU₂, hyV₂, hsub₂⟩
    refine ⟨U₁ ∩ U₂, V₁ ∩ V₂, tX.closed_under_inter _ _ hU₁ hU₂,
      tY.closed_under_inter _ _ hV₁ hV₂,
      ⟨hxU₁, hxU₂⟩, ⟨hyV₁, hyV₂⟩, ?_⟩
    intro q hq
    rcases hq with ⟨⟨hqU₁, hqU₂⟩, ⟨hqV₁, hqV₂⟩⟩
    exact ⟨hsub₁ ⟨hqU₁, hqV₁⟩, hsub₂ ⟨hqU₂, hqV₂⟩⟩

/-! ## Box Topology (finitely many factors coincide with product) -/

def boxTopology (X Y : Type u) [tX : TopologicalSpace X] [tY : TopologicalSpace Y] :
    TopologicalSpace (X × Y) where
  opens := {W | ∀ (x, y) ∈ W, ∃ (U : Set X) (V : Set Y),
    U ∈ tX.opens ∧ V ∈ tY.opens ∧ x ∈ U ∧ y ∈ V ∧ U ×ˢ V ⊆ W}
  contains_univ := (prodTopology X Y).contains_univ
  contains_empty := (prodTopology X Y).contains_empty
  closed_under_union := (prodTopology X Y).closed_under_union
  closed_under_inter := (prodTopology X Y).closed_under_inter

/-! ## Projection Maps -/

def pi1 (X Y : Type u) [tX : TopologicalSpace X] [tY : TopologicalSpace Y] :
    ContinuousMap (X × Y) X where
  toFun := Prod.fst
  continuous V hV := by
    intro p hp
    have hV' : Set.preimage Prod.fst V ∈ (prodTopology X Y).opens := by
      intro q hq
      refine ⟨V, Set.univ, hV, tY.contains_univ, hq, by trivial, ?_⟩
      intro r hr
      exact hr.1
    exact hV' p hp

def pi2 (X Y : Type u) [tX : TopologicalSpace X] [tY : TopologicalSpace Y] :
    ContinuousMap (X × Y) Y where
  toFun := Prod.snd
  continuous V hV := by
    intro p hp
    have hV' : Set.preimage Prod.snd V ∈ (prodTopology X Y).opens := by
      intro q hq
      refine ⟨Set.univ, V, tX.contains_univ, hV, by trivial, hq, ?_⟩
      intro r hr
      exact hr.2
    exact hV' p hp

/-! ## #eval Tests -/

#eval "── Constructions/Products: binary product topology ──"
#check prodTopology
#check boxTopology
#check pi1
#eval "Product topology and projection maps defined"

end MiniTopologicalSpaces
