/-
# MiniTopologicalSpaces: Subspace Topology and Bases

Defines the subspace (relative) topology, subbasis, and basis
generation for topological spaces.
-/

import MiniTopologicalSpaces.Core.Basic
import MiniTopologicalSpaces.Morphisms.Hom

namespace MiniTopologicalSpaces

/-! ## Subspace (Relative) Topology

Given a space X and a subset A ⊆ X, the subspace topology on A
has open sets of the form U ∩ A where U is open in X.
-/

def subspaceTopology {X : Type u} [tX : TopologicalSpace X] (A : Set X) :
    TopologicalSpace (Subtype A) where
  opens := {V : Set (Subtype A) | ∃ (U : Set X), U ∈ tX.opens ∧ V = Subtype.val ⁻¹' U}
  contains_univ := by
    refine ⟨Set.univ, tX.contains_univ, ?_⟩
    ext ⟨x, hx⟩; simp
  contains_empty := by
    refine ⟨∅, tX.contains_empty, ?_⟩
    ext ⟨x, hx⟩; simp
  closed_under_union 𝒰 h := by
    sorry
  closed_under_inter V₁ V₂ hV₁ hV₂ := by
    sorry

/-! ## Subbasis Generation

A subbasis S is a collection of subsets of X.
The topology generated by S is the collection of all unions
of finite intersections of elements of S.
-/

structure Subbasis (X : Type u) where
  sets : Set (Set X)

def generateFromSubbasis {X : Type u} (S : Subbasis X) : TopologicalSpace X :=
  -- Placeholder: the topology generated by S
  discreteTopology X

/-! ## Basis Generation

A basis B is a collection of open sets such that every open set
is a union of basis elements.
-/

structure Basis (X : Type u) [t : TopologicalSpace X] where
  sets : Set (Set X)
  basis_elements_open : ∀ B ∈ sets, B ∈ t.opens
  covers : ∀ U ∈ t.opens, ∃ (𝒱 : Set (Set X)), (∀ V ∈ 𝒱, V ∈ sets) ∧ U = ⋃₀ 𝒱

def generateFromBasis {X : Type u} (B : Set (Set X))
    (h_cover : ⋃₀ B = Set.univ)
    (h_inter : ∀ B₁ B₂, B₁ ∈ B → B₂ ∈ B → B₁ ∩ B₂ ∈ B) : TopologicalSpace X :=
  -- Placeholder: the topology generated by B
  indiscreteTopology X

#eval "── Constructions/Subobjects: subspace topology ──"
#check subspaceTopology
#check Subbasis
#check Basis
#eval "Subspace topology with subbasis and basis generation"

end MiniTopologicalSpaces
