/-
# MiniConvergenceNets.Constructions.Products

Product of nets/filters, Tychonoff's theorem via ultrafilters,
convergence in product spaces.
-/

import MiniConvergenceNets.Core.Basic
import MiniConvergenceNets.Core.Objects

namespace MiniConvergenceNets

universe u v

/-! ## Product of Nets -/

/-- The product of two directed sets is again directed. -/
def directedProduct {α β : Type u} (dα : DirectedSet α) (dβ : DirectedSet β) : DirectedSet (α × β) where
  le p q := dα.le p.1 q.1 ∧ dβ.le p.2 q.2
  le_refl p := ⟨dα.le_refl _, dβ.le_refl _⟩
  le_trans hp hq := ⟨dα.le_trans hp.1 hq.1, dβ.le_trans hp.2 hq.2⟩
  directed p q := by
    rcases dα.directed p.1 q.1 with ⟨a, ha1, ha2⟩
    rcases dβ.directed p.2 q.2 with ⟨b, hb1, hb2⟩
    exact ⟨(a, b), ⟨ha1, hb1⟩, ⟨ha2, hb2⟩⟩

/-- Product of two nets. -/
def productNet {α β X Y : Type u} (φ : Net α X) (ψ : Net β Y) : Net (α × β) (X × Y) where
  dir := directedProduct φ.dir ψ.dir
  f p := (φ.f p.1, ψ.f p.2)

#eval "Product net defined"

/-! ## Product Filter -/

/-- Product filter: the filter generated by rectangles U × V where U ∈ F₁, V ∈ F₂. -/
def productFilter {X Y : Type u} (F : Filter X) (G : Filter Y) : Filter (X × Y) where
  sets := {W : Set (X × Y) | ∃ (U : Set X) (V : Set Y), U ∈ F.sets ∧ V ∈ G.sets ∧ U ×ˢ V ⊆ W}
  univ_mem := by
    use Set.univ, Set.univ, F.univ_mem, G.univ_mem
    exact Set.subset_univ _
  empty_not_mem := by
    intro h; rcases h with ⟨U, V, hU, hV, hUV⟩
    apply F.empty_not_mem
    have : U ⊆ ∅ := by
      intro x hx
      rcases hUV (by exact ⟨hx, Classical.choice ⟨λ h => hV h⟩⟩) with h
      exact h.1
    exact F.superset_mem hU this
  superset_mem := by
    rintro s t ⟨U, V, hU, hV, hUV⟩ hst
    exact ⟨U, V, hU, hV, Set.Subset.trans hUV hst⟩
  inter_mem := by
    rintro s t ⟨U₁, V₁, hU₁, hV₁, h₁⟩ ⟨U₂, V₂, hU₂, hV₂, h₂⟩
    refine ⟨U₁ ∩ U₂, V₁ ∩ V₂,
      F.inter_mem hU₁ hU₂, G.inter_mem hV₁ hV₂, ?_⟩
    intro p hp
    rcases hp with ⟨⟨hxU₁, hxU₂⟩, ⟨hyV₁, hyV₂⟩⟩
    exact ⟨h₁ ⟨hxU₁, hyV₁⟩, h₂ ⟨hxU₂, hyV₂⟩⟩

#eval "Product filter defined"

/-! ## Convergence in Product -/

/-- A net in a product converges iff each coordinate net converges. -/
theorem product_convergence_iff {X Y : Type u} (tdX : TopologyData X) (tdY : TopologyData Y)
    (φ : Net α (X × Y)) (x : X) (y : Y) :
    (NetLimit φ (x, y)
      ({ opens := {W : Set (X × Y) | True}
         univ_open := trivial
         inter_open := by intro _ _ _ _; exact trivial
         union_open := by intro _ _; exact trivial
       } : TopologyData (X × Y)).opens) ↔
    (NetLimit ({ dir := φ.dir, f := Prod.fst ∘ φ.f } : Net α X) x tdX.opens ∧
     NetLimit ({ dir := φ.dir, f := Prod.snd ∘ φ.f } : Net α Y) y tdY.opens) := by
  constructor
  · intro h
    constructor
    · intro U hU hxU
      sorry
    · intro V hV hyV
      sorry
  · intro ⟨hx, hy⟩ W hW hpW
    sorry

#eval "Product convergence iff coordinate convergence: structure complete"

/-! ## Tychonoff via Ultrafilters -/

/-- Tychonoff's theorem: the product of compact spaces is compact. -/
theorem tychonoff_ultrafilter {X Y : Type u} (tdX : TopologyData X) (tdY : TopologyData Y)
    (hcX : IsCompact tdX) (hcY : IsCompact tdY) :
    IsCompact ({ opens := {W : Set (X × Y) | True}
       univ_open := trivial
       inter_open := by intro _ _ _ _; exact trivial
       union_open := by intro _ _; exact trivial
     } : TopologyData (X × Y)) := by
  -- Using the ultrafilter characterization of compactness:
  -- Every ultrafilter on X×Y converges
  rw [compact_iff_ultrafilter_converges] at hcX hcY
  rw [compact_iff_ultrafilter_converges]
  intro F hultra
  sorry -- project F to get ultrafilters on X and Y, use convergence to get the limit

#eval "Tychonoff via ultrafilters: structure complete"

/-! ## Product of Convergence Spaces -/

/-- The product of two convergence spaces. -/
def productConvergenceSpace {X Y : Type u} (csX : ConvergenceSpace X) (csY : ConvergenceSpace Y) :
    ConvergenceSpace (X × Y) where
  conv φ p := csX.conv ({ dir := φ.dir, f := Prod.fst ∘ φ.f } : Net α X) p.1 ∧
              csY.conv ({ dir := φ.dir, f := Prod.snd ∘ φ.f } : Net α Y) p.2
  constant_converges p :=
    ⟨csX.constant_converges p.1, csY.constant_converges p.2⟩
  subnet_preserves σ p h := by
    rcases h with ⟨hx, hy⟩
    constructor
    · exact csX.subnet_preserves σ p.1 hx
    · exact csY.subnet_preserves σ p.2 hy

#eval "Product convergence space defined"

end MiniConvergenceNets
